from typing import Dict, List, Optional
from backend.rule_engine.models import StatutoryRuleDefinition, SeverityLevel
from backend.rule_engine.legal_provenance import LEGAL_PROVENANCE_REGISTRY

STATUTORY_RULE_REGISTRY: Dict[str, StatutoryRuleDefinition] = {
    "PCR_RULE_06_1_E": StatutoryRuleDefinition(
        rule_code="PCR_RULE_06_1_E",
        rule_version=1,
        title="Maximum Retail Price (MRP) Declaration",
        category="CATEGORY_A_LEGAL",
        statutory_reference="Rule 6(1)(e) read with Rule 2(m), Legal Metrology (Packaged Commodities) Rules, 2011 (PDF p. 3, 6)",
        description="Mandatory declaration of retail sale price in Indian Rupees inclusive of all taxes.",
        severity=SeverityLevel.CRITICAL,
        required_fields=["mrp"],
        exact_pdf_page=6,
        exact_section="Chapter II, Rule 6(1)(e) (p. 6); Chapter I, Rule 2(m) (p. 3)",
        applicability_conditions="Applicable to all pre-packaged commodities intended for retail sale.",
        statutory_exceptions="Bidi and domestic LPG under Administered Price Mechanism (Rule 6(1) proviso (C), p. 7).",
        evaluation_logic="Verifies numerical retail price accompanied by mandatory statutory tax qualifier 'inclusive of all taxes'.",
        verification_status="STATUTORY_VERIFIED"
    ),
    "PCR_RULE_06_1_A": StatutoryRuleDefinition(
        rule_code="PCR_RULE_06_1_A",
        rule_version=1,
        title="Name & Address of Manufacturer / Packer / Importer",
        category="CATEGORY_A_LEGAL",
        statutory_reference="Rule 6(1)(a) & Explanations I-II, Legal Metrology (Packaged Commodities) Rules, 2011 (PDF p. 5)",
        description="Mandatory declaration of the name and complete address of the manufacturer, packer, or importer (including brand owner as deemed manufacturer).",
        severity=SeverityLevel.CRITICAL,
        required_fields=["manufacturer_details"],
        exact_pdf_page=5,
        exact_section="Chapter II, Rule 6(1)(a) & Explanations I, II (p. 5); Rule 10 (p. 10-11)",
        applicability_conditions="Applicable to all pre-packaged commodities intended for retail sale.",
        statutory_exceptions="Packages <= 5 cubic cm may bear identifying inscription (Rule 10(1) proviso, p. 11).",
        evaluation_logic="Verifies manufacturer/packer/marketer name and complete postal address with PIN code or city/state.",
        verification_status="STATUTORY_VERIFIED"
    ),
    "PCR_RULE_06_1_C": StatutoryRuleDefinition(
        rule_code="PCR_RULE_06_1_C",
        rule_version=1,
        title="Net Quantity Declaration in Standard Metric Units",
        category="CATEGORY_A_LEGAL",
        statutory_reference="Rule 6(1)(c) read with Rules 11, 12, 13 & Second Schedule, Legal Metrology (Packaged Commodities) Rules, 2011 (PDF p. 5, 11-14, 29-32)",
        description="Mandatory declaration of net weight, volume, or measure in standard SI units (kg, g, L, ml, count).",
        severity=SeverityLevel.CRITICAL,
        required_fields=["net_quantity"],
        exact_pdf_page=5,
        exact_section="Chapter II, Rule 6(1)(c) (p. 5); Rules 11-13 (p. 11-14); Second Schedule (p. 29-32)",
        applicability_conditions="Applicable to all retail packages exceeding 10g/10ml (Rule 26(a), p. 24).",
        statutory_exceptions="Packages containing 10g or 10ml or less exempt under Rule 26(a) (p. 24).",
        evaluation_logic="Verifies numerical net quantity with standard SI metric unit. Checks against Second Schedule standard pack sizes.",
        verification_status="STATUTORY_VERIFIED"
    ),
    "PCR_RULE_06_1_D": StatutoryRuleDefinition(
        rule_code="PCR_RULE_06_1_D",
        rule_version=1,
        title="Month and Year of Manufacture / Packing",
        category="CATEGORY_A_LEGAL",
        statutory_reference="Rule 6(1)(d) & Explanation I, Legal Metrology (Packaged Commodities) Rules, 2011 (PDF p. 5, 7)",
        description="Mandatory declaration of the month and year in which the commodity is manufactured, packed, or imported.",
        severity=SeverityLevel.MAJOR,
        required_fields=["date_of_manufacture_packing"],
        exact_pdf_page=5,
        exact_section="Chapter II, Rule 6(1)(d) (p. 5) & Explanation I (p. 7)",
        applicability_conditions="Applicable to all pre-packaged commodities intended for retail sale.",
        statutory_exceptions="Bidis, incense sticks, and domestic LPG cylinders exempt under Rule 6(1) proviso (A) (p. 6).",
        evaluation_logic="Verifies valid structural date representation for month and year of manufacture/packing.",
        verification_status="STATUTORY_VERIFIED"
    ),
    "PCR_RULE_06_1_G": StatutoryRuleDefinition(
        rule_code="PCR_RULE_06_1_G",
        rule_version=1,
        title="Consumer Care Grievance Redressal Details",
        category="CATEGORY_A_LEGAL",
        statutory_reference="Rule 6(2), Legal Metrology (Packaged Commodities) Rules, 2011 (PDF p. 7)",
        description="Mandatory declaration of name, address, telephone number, and e-mail of contact person for consumer complaints.",
        severity=SeverityLevel.MAJOR,
        required_fields=["consumer_care_details"],
        exact_pdf_page=7,
        exact_section="Chapter II, Rule 6(2) (p. 7)",
        applicability_conditions="Applicable to all pre-packaged commodities intended for retail sale.",
        statutory_exceptions="E-mail address required 'if available' under Rule 6(2).",
        evaluation_logic="Verifies presence of contact person/office, phone number, and/or email address for consumer grievances.",
        verification_status="STATUTORY_VERIFIED"
    ),
    "PCR_RULE_06_1_F": StatutoryRuleDefinition(
        rule_code="PCR_RULE_06_1_F",
        rule_version=1,
        title="Generic Name or Commodity Identification",
        category="CATEGORY_A_LEGAL",
        statutory_reference="Rule 6(1)(b), Legal Metrology (Packaged Commodities) Rules, 2011 (PDF p. 5)",
        description="Mandatory declaration of common or generic name of commodity on the package.",
        severity=SeverityLevel.MAJOR,
        required_fields=["commodity_name"],
        exact_pdf_page=5,
        exact_section="Chapter II, Rule 6(1)(b) (p. 5)",
        applicability_conditions="Applicable to all pre-packaged commodities intended for retail sale.",
        statutory_exceptions="None for standard retail packages.",
        evaluation_logic="Verifies declaration of common or generic commodity name on the package.",
        verification_status="STATUTORY_VERIFIED"
    ),
    "PCR_RULE_06_1_B": StatutoryRuleDefinition(
        rule_code="PCR_RULE_06_1_B",
        rule_version=1,
        title="Country of Origin Declaration",
        category="CATEGORY_A_LEGAL",
        statutory_reference="Rule 6(1)(a) Proviso & Rule 10(1), Legal Metrology (Packaged Commodities) Rules, 2011 (PDF p. 5, 11)",
        description="Mandatory declaration of the country of origin for imported commodities or where mandated by law.",
        severity=SeverityLevel.MAJOR,
        required_fields=["country_of_origin"],
        exact_pdf_page=5,
        exact_section="Chapter II, Rule 6(1)(a) (p. 5); Rule 10(1) (p. 11)",
        applicability_conditions="Mandatory for imported commodities. Indian address alone does NOT establish domestic origin.",
        statutory_exceptions="Domestic commodities where manufacture and packing occurred in India.",
        evaluation_logic="Checks if explicitly declared. If not declared, requires inspector manual verification to determine import/domestic status.",
        verification_status="NEEDS_LEGAL_VERIFICATION"
    ),
    "PCR_RULE_UNIT_SALE_PRICE": StatutoryRuleDefinition(
        rule_code="PCR_RULE_UNIT_SALE_PRICE",
        rule_version=1,
        title="Unit Sale Price (USP) Declaration",
        category="CATEGORY_A_LEGAL",
        statutory_reference="Subsequent Amendment (GSR 779(E) dated 02.11.2021) - Not in 2011 PDF (GSR 202(E))",
        description="Declaration of unit sale price (e.g. Rs. per g/kg/ml). Mandated by 2021 amendment.",
        severity=SeverityLevel.MINOR,
        required_fields=["unit_sale_price"],
        exact_pdf_page=0,
        exact_section="Not present in original 2011 Rules PDF. Enacted via 2021 amendment GSR 779(E).",
        applicability_conditions="Mandated under 2021 amendment for packages with net quantity exceeding 1 kg/1 L, or smaller sizes.",
        statutory_exceptions="Not applicable under principal 2011 rules.",
        evaluation_logic="Extracted independently from OCR evidence. Marked as NEEDS_LEGAL_VERIFICATION against the 2011 PDF source.",
        verification_status="NEEDS_LEGAL_VERIFICATION"
    ),
    "DATA_QUAL_PHONE_SYNTAX": StatutoryRuleDefinition(
        rule_code="DATA_QUAL_PHONE_SYNTAX",
        rule_version=1,
        title="Consumer Care Telephone Syntax Verification",
        category="CATEGORY_B_DATA_QUALITY",
        statutory_reference="Rule 6(2) Standards & DoCA Guidelines, Legal Metrology (Packaged Commodities) Rules, 2011 (PDF p. 7)",
        description="Verifies that telephone numbers conform to 10-digit mobile/landline or 1800 toll-free formats.",
        severity=SeverityLevel.MINOR,
        required_fields=["consumer_care_details"],
        exact_pdf_page=7,
        exact_section="Chapter II, Rule 6(2) (p. 7)",
        applicability_conditions="Applicable whenever consumer telephone number is declared.",
        statutory_exceptions="None.",
        evaluation_logic="Verifies valid telephone formatting (10-digit mobile or 1800 toll-free).",
        verification_status="STATUTORY_VERIFIED"
    ),
    "DATA_QUAL_DATE_PLAUSIBILITY": StatutoryRuleDefinition(
        rule_code="DATA_QUAL_DATE_PLAUSIBILITY",
        rule_version=1,
        title="Manufacturing Date Plausibility & Syntax Check",
        category="CATEGORY_B_DATA_QUALITY",
        statutory_reference="Rule 6(1)(d) General Standards, Legal Metrology (Packaged Commodities) Rules, 2011 (PDF p. 5, 7)",
        description="Verifies that manufacturing date is structurally plausible and not future-dated beyond statutory limits.",
        severity=SeverityLevel.MINOR,
        required_fields=["date_of_manufacture_packing"],
        exact_pdf_page=5,
        exact_section="Chapter II, Rule 6(1)(d) (p. 5) & Explanation I (p. 7)",
        applicability_conditions="Applicable to all date declarations.",
        statutory_exceptions="None.",
        evaluation_logic="Verifies date syntax and chronological plausibility.",
        verification_status="STATUTORY_VERIFIED"
    ),
    "PCR_RULE_06_10_ECOMMERCE_DECLARATION": StatutoryRuleDefinition(
        rule_code="PCR_RULE_06_10_ECOMMERCE_DECLARATION",
        rule_version=1,
        title="E-Commerce Mandatory Declarations Display",
        category="CATEGORY_A_LEGAL",
        statutory_reference="Rule 6(10), Legal Metrology (Packaged Commodities) Rules, 2011 (GSR 629(E))",
        description="Mandatory display on digital and e-commerce platforms of all Rule 6(1) declarations (except month and year of manufacture/packing) prior to retail sale.",
        severity=SeverityLevel.MAJOR,
        required_fields=["product_name", "mrp", "net_quantity", "manufacturer_details", "country_of_origin", "consumer_care_details"],
        exact_pdf_page=0,
        exact_section="Chapter II, Rule 6(10) (GSR 629(E))",
        applicability_conditions="Applicable to all packaged commodities offered for sale on digital or e-commerce networks.",
        statutory_exceptions="Month and year of manufacture or packing is exempt from e-commerce display under Rule 6(10) proviso.",
        evaluation_logic="Verifies that all mandatory declarations established on the physical package are accurately and completely disclosed on the product listing.",
        verification_status="STATUTORY_VERIFIED"
    ),
    "PCR_RULE_18_2A_ONLINE_PRICE_OVERCHARGING": StatutoryRuleDefinition(
        rule_code="PCR_RULE_18_2A_ONLINE_PRICE_OVERCHARGING",
        rule_version=1,
        title="Prohibition of Sale Above Package MRP",
        category="CATEGORY_A_LEGAL",
        statutory_reference="Rule 18(2A) read with Section 36(1), Legal Metrology (Packaged Commodities) Rules, 2011",
        description="Strict statutory prohibition against declaring or selling a pre-packaged commodity on an online platform at a price exceeding the Maximum Retail Price (MRP) marked on the physical package.",
        severity=SeverityLevel.CRITICAL,
        required_fields=["mrp"],
        exact_pdf_page=0,
        exact_section="Chapter II, Rule 18(2A)",
        applicability_conditions="Applicable to all online listings and marketplace offerings of pre-packaged commodities.",
        statutory_exceptions="None. Sale above printed MRP is strictly prohibited under Legal Metrology Act.",
        evaluation_logic="Compares online listing price against physical package OCR MRP. Flags discrepancies where online listing exceeds physical package MRP.",
        verification_status="STATUTORY_VERIFIED"
    )
}

def get_all_rules() -> List[StatutoryRuleDefinition]:
    return list(STATUTORY_RULE_REGISTRY.values())

def get_rule_by_code(rule_code: str) -> Optional[StatutoryRuleDefinition]:
    return STATUTORY_RULE_REGISTRY.get(rule_code)
